service: bcparks-ar-api

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  stage: api
  region: ca-central-1
  lambdaHashingVersion: 20201221

package:
  individually: true
  patterns:
    - "!./**" # This causes Serverless to only package referenced source files

plugins:
  - serverless-offline
  - serverless-plugin-include-dependencies
functions:
  ###########
  # readConfig
  ###########
  readConfig:
    handler: lambda/readConfig/index.handler
    events:
      - http:
          method: GET
          path: /config

  ###########
  # Park
  ###########
  parkGet:
    handler: lambda/park/GET/index.handler
    events:
      - http:
          method: GET
          path: /park
          cors: true

  parkPost:
    handler: lambda/park/POST/index.handler
    events:
      - http:
          method: POST
          path: /park
          cors: true

  parkPut:
    handler: lambda/park/PUT/index.handler
    events:
      - http:
          method: PUT
          path: /park
          cors: true

  # ###########
  # # SubArea
  # ###########
  subAreaGet:
    handler: lambda/subArea/GET/index.handler
    events:
      - http:
          method: GET
          path: /subArea
          cors: true

  subAreaPost:
    handler: lambda/subArea/POST/index.handler
    events:
      - http:
          method: POST
          path: /subArea
          cors: true

  subAreaPut:
    handler: lambda/subArea/PUT/index.handler
    events:
      - http:
          method: PUT
          path: /subArea
          cors: true

  ###########
  # Activity
  ###########
  activityGet:
    handler: lambda/activity/GET/index.handler
    events:
      - http:
          method: GET
          path: /activity
          cors: true

  activityPost:
    handler: lambda/activity/POST/index.handlePost
    events:
      - http:
          method: POST
          path: /activity
          cors: true

  activityPut:
    handler: lambda/activity/PUT/index.handler
    events:
      - http:
          method: PUT
          path: /activity
          cors: true

  activityRecordLock:
    handler: lambda/activity/POST/index.handleLock
    events:
      - http:
          method: POST
          path: /activity/lock
          cors: true

  activityRecordUnlock:
    handler: lambda/activity/POST/index.handleUnlock
    events:
      - http:
          method: POST
          path: /activity/unlock
          cors: true

  ###########
  # Cloudwatch Alarm
  ###########
  cloudwatchAlarm:
    handler: lambda/cloudwatchAlarm/index.handler

  ###########
  # Export
  ###########
  exportInvokable:
    handler: lambda/export/invokable/index.handler
  exportGet:
    handler: lambda/export/GET/index.handler
    events:
      - http:
          method: GET
          path: /export
          cors: true

  ###########
  # Fiscal Year End
  ###########
  fiscalYearEndGet:
    handler: lambda/fiscalYearEnd/GET/index.handler
    events:
      - http:
          method: GET
          path: /fiscalYearEnd
          cors: true

  fiscalYearEndLock:
    handler: lambda/fiscalYearEnd/POST/index.lockFiscalYear
    events:
      - http:
          method: POST
          path: /fiscalYearEnd/lock
          cors: true

  fiscalYearEndUnlock:
    handler: lambda/fiscalYearEnd/POST/index.unlockFiscalYear
    events:
      - http:
          method: POST
          path: /fiscalYearEnd/unlock
          cors: true

resources:
  Resources:
    databaseTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        TableName: arTable
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
